# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: showroom_matic21
#   pool: 5
#   username: root
#   password: 123456
#   host: localhost
#   port: 3306

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: showroom_matic_development
#   pool: 5
#   username: root
#   password: 123456
#   host: localhost
#   port: 3306

development:
  adapter: sqlite3
  database: development
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: test
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: production
  pool: 5
  timeout: 5000