# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
 admin = User.create(
    :email => "admin@gmail.com",
    :password => "12345678",
    :password_confirmation => "12345678",
    :first_name => "admin",
    :last_name => "admin",
    :admin => true,
    :terms_accepted => true,
    :country_id => '1'
)
 dealer = User.create(
    :email => "dealer@gmail.com",
    :password => "12345678",
    :password_confirmation => "12345678",
    :first_name => "dealer",
    :last_name => "dealer",
    :dealer => "dealer",
    :terms_accepted => true,
    :country_id => '1'
)

Role.create([ 
      {:role => "Seeking Capital"},
      {:role => "Free Agent"},
      {:role => "Job Posting"},
      {:role => "Intern"}
      ])

# Order.delete_all
# Order.create  name: "indore", address: "indore", email: "indore@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "ram", address: "indore", email: "ram@gmail.com", pay_type: "Purchase order",  total_amount: 49.5
# Order.create  name: "goa", address: "goa", email: "sandeepchourey@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "sandeepchourey", address: "indore", email: "sandeepchourey@gmail.com", pay_type: "Check",  total_amount: 49.5
# Order.create  name: "sandy", address: "delhi", email: "sandy@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "sandeepchourey", address: "goa", email: "raju@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "raju", address: "indore", email: "raju@gmail.com", pay_type: "Purchase order",  total_amount: 49.5
# Order.create  name: "raju", address: "goa", email: "sandeepchourey@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "sandeepchourey", address: "delhi", email: "raju@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "raju", address: "delhi", email: "sandeepchourey@gmail.com", pay_type: "Check",  total_amount: 49.5
# Order.create  name: "goa", address: "indore", email: "sandeepchourey@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "sandeepchourey", address: "indore", email: "sandeepchourey@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "shyam", address: "delhi", email: "shyam@gmail.com", pay_type: "Credit card",  total_amount: 49.5
# Order.create  name: "shyam", address: "goa", email: "ram@gmail.com", pay_type: "Check", total_amount: 49.5

countries = CountryList.create([
                    {:name => 'AFGHANISTAN', :iso => 'AFG', :phonecode => 93},
                              {:name => 'Åland Islands', :iso => 'AX', :phonecode => 358},
                              {:name => 'Albania', :iso => 'AL', :phonecode => 355},
                              {:name => 'Algeria', :iso => 'DZ', :phonecode => 213},
                              {:name => 'American Samoa', :iso => 'AS', :phonecode => 1684},
                              {:name => 'Andorra', :iso => 'AD', :phonecode => 376},
                              {:name => 'Angola', :iso => 'AO', :phonecode => 244},
                              {:name => 'Anguilla', :iso => 'AI', :phonecode => 1264},
                              {:name => 'Antarctica', :iso => 'AQ', :phonecode => 0},
                              {:name => 'Antigua and Barbuda', :iso => 'AG', :phonecode => 1268},
                              {:name => 'Argentina', :iso => 'AR', :phonecode => 54},
                              {:name => 'Armenia', :iso => 'AM', :phonecode => 374},
                              {:name => 'Aruba', :iso => 'AW', :phonecode => 297},
                              {:name => 'Australia', :iso => 'AU', :phonecode => 61},
                              {:name => 'Austria', :iso => 'AT', :phonecode => 43},
                              {:name => 'Azerbaijan', :iso => 'AZ', :phonecode => 994},
                              {:name => 'Bahamas', :iso => 'BS', :phonecode => 1242},
                              {:name => 'Bahrain', :iso => 'BH', :phonecode => 973},
                              {:name => 'Bangladesh', :iso => 'BD', :phonecode => 880},
                              {:name => 'Barbados', :iso => 'BB', :phonecode => 1246},
                              {:name => 'Belarus', :iso => 'BY', :phonecode => 375},
                              {:name => 'Belgium', :iso => 'BE', :phonecode => 32},
                              {:name => 'Belize', :iso => 'BZ', :phonecode => 501},
                              {:name => 'Benin', :iso => 'BJ', :phonecode => 229},
                              {:name => 'Bermuda', :iso => 'BM', :phonecode => 1441},
                              {:name => 'Bhutan', :iso => 'BT', :phonecode => 975},
                              {:name => 'Bolivia', :iso => 'BO', :phonecode => 591},
                              {:name => 'Bosnia and Herzegovina', :iso => 'BA', :phonecode => 387},
                              {:name => 'Botswana', :iso => 'BW', :phonecode => 267},
                              {:name => 'Bouvet Island', :iso => 'BV', :phonecode => 0},
                              {:name => 'Brazil', :iso => 'BR', :phonecode => 55},
                              {:name => 'British Indian Ocean Territory', :iso => 'IO', :phonecode => 246},
                              {:name => 'Brunei Darussalam', :iso => 'BN', :phonecode => 673},
                              {:name => 'Bulgaria', :iso => 'BG', :phonecode => 359},
                              {:name => 'Burkina Faso', :iso => 'BF', :phonecode => 226},
                              {:name => 'Burundi', :iso => 'BI', :phonecode => 257},
                              {:name => 'Cambodia', :iso => 'KH', :phonecode => 855},
                              {:name => 'Cameroon', :iso => 'CM', :phonecode => 237},
                              {:name => 'Canada', :iso => 'CA', :phonecode => 1},
                              {:name => 'Cape Verde', :iso => 'CV', :phonecode => 238},
                              {:name => 'Cayman Islands', :iso => 'KY', :phonecode => 1345},
                              {:name => 'Central African Republic', :iso => 'CF', :phonecode => 236},
                              {:name => 'Chad', :iso => 'TD', :phonecode => 235},
                              {:name => 'Chile', :iso => 'CL', :phonecode => 56},
                              {:name => 'China', :iso => 'CN', :phonecode => 86},
                              {:name => 'Christmas Island', :iso => 'CX', :phonecode => 61},
                              {:name => 'Cocos (Keeling) Islands', :iso => 'CC', :phonecode => 672},
                              {:name => 'Colombia', :iso => 'CO', :phonecode => 57},
                              {:name => 'Comoros', :iso => 'KM', :phonecode => 269},
                              {:name => 'Congo', :iso => 'CG', :phonecode => 242},
                              {:name => 'Congo, The Democratic Republic of The', :iso => 'CD', :phonecode => 242},
                              {:name => 'Cook Islands', :iso => 'CK', :phonecode => 682},
                              {:name => 'Costa Rica', :iso => 'CR', :phonecode => 506},
                              {:name => 'Côte D\'Ivoire', :iso => 'CI', :phonecode => 225},
                              {:name => 'Croatia', :iso => 'HR', :phonecode => 385},
                              {:name => 'Cuba', :iso => 'CU', :phonecode => 53},
                              {:name => 'Cyprus', :iso => 'CY', :phonecode => 357},
                              {:name => 'Czech Republic', :iso => 'CZ', :phonecode => 420},
                              {:name => 'Denmark', :iso => 'DK', :phonecode => 45},
                              {:name => 'Djibouti', :iso => 'DJ', :phonecode => 253},
                              {:name => 'Dominica', :iso => 'DM', :phonecode => 1767},
                              {:name => 'Dominican Republic', :iso => 'DO', :phonecode => 1809},
                              {:name => 'Ecuador', :iso => 'EC', :phonecode => 593},
                              {:name => 'Egypt', :iso => 'EG', :phonecode => 20},
                              {:name => 'El Salvador', :iso => 'SV', :phonecode => 503},
                              {:name => 'Equatorial Guinea', :iso => 'GQ', :phonecode => 240},
                              {:name => 'Eritrea', :iso => 'ER', :phonecode => 291},
                              {:name => 'Estonia', :iso => 'EE', :phonecode => 372},
                              {:name => 'Ethiopia', :iso => 'ET', :phonecode => 251},
                              {:name => 'Falkland Islands (Malvinas)', :iso => 'FK', :phonecode => 500},
                              {:name => 'Faroe Islands', :iso => 'FO', :phonecode => 298},
                              {:name => 'Fiji', :iso => 'FJ', :phonecode => 679},
                              {:name => 'Finland', :iso => 'FI', :phonecode => 358},
                              {:name => 'France', :iso => 'FR', :phonecode => 33},
                              {:name => 'French Guiana', :iso => 'GF', :phonecode => 594},
                              {:name => 'French Polynesia', :iso => 'PF', :phonecode => 689},
                              {:name => 'French Southern Territories', :iso => 'TF', :phonecode => 0},
                              {:name => 'Gabon', :iso => 'GA', :phonecode => 241},
                              {:name => 'Gambia', :iso => 'GM', :phonecode => 220},
                              {:name => 'Georgia', :iso => 'GE', :phonecode => 995},
                              {:name => 'Germany', :iso => 'DE', :phonecode => 49},
                              {:name => 'Ghana', :iso => 'GH', :phonecode => 233},
                              {:name => 'Gibraltar', :iso => 'GI', :phonecode => 350},
                              {:name => 'Greece', :iso => 'GR', :phonecode => 30},
                              {:name => 'Greenland', :iso => 'GL', :phonecode => 299},
                              {:name => 'Grenada', :iso => 'GD', :phonecode => 1473},
                              {:name => 'Guadeloupe', :iso => 'GP', :phonecode => 590},
                              {:name => 'Guam', :iso => 'GU', :phonecode => 1671},
                              {:name => 'Guatemala', :iso => 'GT', :phonecode => 502},
                              {:name => 'Guernsey', :iso => 'GG', :phonecode => 44},
                              {:name => 'Guinea', :iso => 'GN', :phonecode => 224},
                              {:name => 'Guinea-Bissau', :iso => 'GW', :phonecode => 245},
                              {:name => 'Guyana', :iso => 'GY', :phonecode => 592},
                              {:name => 'Haiti', :iso => 'HT', :phonecode => 509},
                              {:name => 'Heard Island and Mcdonald Islands', :iso => 'HM', :phonecode => 0},
                              {:name => 'Holy See (Vatican City State)', :iso => 'VA', :phonecode => 39},
                              {:name => 'Honduras', :iso => 'HN', :phonecode => 504},
                              {:name => 'Hong Kong', :iso => 'HK', :phonecode => 852},
                              {:name => 'Hungary', :iso => 'HU', :phonecode => 36},
                              {:name => 'Iceland', :iso => 'IS', :phonecode => 354},
                              {:name => 'India', :iso => 'IN', :phonecode => 91},
                              {:name => 'Indonesia', :iso => 'ID', :phonecode => 62},
                              {:name => 'Iran, Islamic Republic of', :iso => 'IR', :phonecode => 98},
                              {:name => 'Iraq', :iso => 'IQ', :phonecode => 964},
                              {:name => 'Ireland', :iso => 'IE', :phonecode => 353},
                              {:name => 'Isle of Man', :iso => 'IM', :phonecode => 44},
                              {:name => 'Israel', :iso => 'IL', :phonecode => 972},
                              {:name => 'Italy', :iso => 'IT', :phonecode => 39},
                              {:name => 'Jamaica', :iso => 'JM', :phonecode => 1876},
                              {:name => 'Japan', :iso => 'JP', :phonecode => 81},
                              {:name => 'Jersey', :iso => 'JE', :phonecode => 962},
                              {:name => 'Jordan', :iso => 'JO', :phonecode => 44},
                              {:name => 'Kazakhstan', :iso => 'KZ', :phonecode => 7},
                              {:name => 'Kenya', :iso => 'KE', :phonecode => 254},
                              {:name => 'Kiribati', :iso => 'KI', :phonecode => 686},
                              {:name => 'Korea, Democratic People\'s Republic of', :iso => 'KP', :phonecode => 850},
                              {:name => 'Korea, Republic of', :iso => 'KR', :phonecode => 82},
                              {:name => 'Kuwait', :iso => 'KW', :phonecode => 965},
                              {:name => 'Kyrgyzstan', :iso => 'KG', :phonecode => 996},
                              {:name => 'Lao People\'s Democratic Republic', :iso => 'LA', :phonecode => 856},
                              {:name => 'Latvia', :iso => 'LV', :phonecode => 371},
                              {:name => 'Lebanon', :iso => 'LB', :phonecode => 961},
                              {:name => 'Lesotho', :iso => 'LS', :phonecode => 266},
                              {:name => 'Liberia', :iso => 'LR', :phonecode => 231},
                              {:name => 'Libyan Arab Jamahiriya', :iso => 'LY', :phonecode => 218},
                              {:name => 'Liechtenstein', :iso => 'LI', :phonecode => 423},
                              {:name => 'Lithuania', :iso => 'LT', :phonecode => 370},
                              {:name => 'Luxembourg', :iso => 'LU', :phonecode => 352},
                              {:name => 'Macao', :iso => 'MO', :phonecode => 853},
                              {:name => 'Macedonia, The Former Yugoslav Republic of', :iso => 'MK', :phonecode => 389},
                              {:name => 'Madagascar', :iso => 'MG', :phonecode => 261},
                              {:name => 'Malawi', :iso => 'MW', :phonecode => 265},
                              {:name => 'Malaysia', :iso => 'MY', :phonecode => 60},
                              {:name => 'Maldives', :iso => 'MV', :phonecode => 960},
                              {:name => 'Mali', :iso => 'ML', :phonecode => 223},
                              {:name => 'Malta', :iso => 'MT', :phonecode => 356},
                              {:name => 'Marshall Islands', :iso => 'MH', :phonecode => 692},
                              {:name => 'Martinique', :iso => 'MQ', :phonecode => 596},
                              {:name => 'Mauritania', :iso => 'MR', :phonecode => 222},
                              {:name => 'Mauritius', :iso => 'MU', :phonecode => 230},
                              {:name => 'Mayotte', :iso => 'YT', :phonecode => 269},
                              {:name => 'Mexico', :iso => 'MX', :phonecode => 52},
                              {:name => 'Micronesia, Federated States of', :iso => 'FM', :phonecode => 691},
                              {:name => 'Moldova, Republic of', :iso => 'MD', :phonecode => 373},
                              {:name => 'Monaco', :iso => 'MC', :phonecode => 377},
                              {:name => 'Mongolia', :iso => 'MN', :phonecode => 976},
                              {:name => 'Montenegro', :iso => 'ME', :phonecode => 381},
                              {:name => 'Montserrat', :iso => 'MS', :phonecode => 1664},
                              {:name => 'Morocco', :iso => 'MA', :phonecode => 212},
                              {:name => 'Mozambique', :iso => 'MZ', :phonecode => 258},
                              {:name => 'Myanmar', :iso => 'MM', :phonecode => 95},
                              {:name => 'Namibia', :iso => 'NA', :phonecode => 264},
                              {:name => 'Nauru', :iso => 'NR', :phonecode => 674},
                              {:name => 'Nepal', :iso => 'NP', :phonecode => 977},
                              {:name => 'Netherlands', :iso => 'NL', :phonecode => 31},
                              {:name => 'Netherlands Antilles', :iso => 'AN', :phonecode => 599},
                              {:name => 'New Caledonia', :iso => 'NC', :phonecode => 687},
                              {:name => 'New Zealand', :iso => 'NZ', :phonecode => 64},
                              {:name => 'Nicaragua', :iso => 'NI', :phonecode => 505},
                              {:name => 'Niger', :iso => 'NE', :phonecode => 227},
                              {:name => 'Nigeria', :iso => 'NG', :phonecode => 234},
                              {:name => 'Niue', :iso => 'NU', :phonecode => 683},
                              {:name => 'Norfolk Island', :iso => 'NF', :phonecode => 672},
                              {:name => 'Northern Mariana Islands', :iso => 'MP', :phonecode => 1670},
                              {:name => 'Norway', :iso => 'NO', :phonecode => 47},
                              {:name => 'Oman', :iso => 'OM', :phonecode => 968},
                              {:name => 'Pakistan', :iso => 'PK', :phonecode => 92},
                              {:name => 'Palau', :iso => 'PW', :phonecode => 680},
                              {:name => 'Palestinian Territory, Occupied', :iso => 'PS', :phonecode => 970},
                              {:name => 'Panama', :iso => 'PA', :phonecode => 507},
                              {:name => 'Papua New Guinea', :iso => 'PG', :phonecode => 675},
                              {:name => 'Paraguay', :iso => 'PY', :phonecode => 595},
                              {:name => 'Peru', :iso => 'PE', :phonecode => 51},
                              {:name => 'Philippines', :iso => 'PH', :phonecode => 63},
                              {:name => 'Pitcairn', :iso => 'PN', :phonecode => 0},
                              {:name => 'Poland', :iso => 'PL', :phonecode => 48},
                              {:name => 'Portugal', :iso => 'PT', :phonecode => 351},
                              {:name => 'Puerto Rico', :iso => 'PR', :phonecode => 1787},
                              {:name => 'Qatar', :iso => 'QA', :phonecode => 974},
                              {:name => 'Réunion', :iso => 'RE', :phonecode => 262},
                              {:name => 'Romania', :iso => 'RO', :phonecode => 40},
                              {:name => 'Russian Federation', :iso => 'RU', :phonecode => 70},
                              {:name => 'Rwanda', :iso => 'RW', :phonecode => 250},
                              {:name => 'Saint Barthélemy', :iso => 'BL', :phonecode => 290},
                              {:name => 'Saint Helena, Ascension and Tristan Da Cunha', :iso => 'SH', :phonecode => 0},
                              {:name => 'Saint Kitts and Nevis', :iso => 'KN', :phonecode => 1869},
                              {:name => 'Saint Lucia', :iso => 'LC', :phonecode => 1758},
                              {:name => 'Saint Martin', :iso => 'MF', :phonecode => 590},
                              {:name => 'Saint Pierre and Miquelon', :iso => 'PM', :phonecode => 508},
                              {:name => 'Saint Vincent and The Grenadines', :iso => 'VC', :phonecode => 1784},
                              {:name => 'Samoa', :iso => 'WS', :phonecode => 684},
                              {:name => 'San Marino', :iso => 'SM', :phonecode => 378},
                              {:name => 'Sao Tome and Principe', :iso => 'ST', :phonecode => 239},
                              {:name => 'Saudi Arabia', :iso => 'SA', :phonecode => 966},
                              {:name => 'Senegal', :iso => 'SN', :phonecode => 221},
                              {:name => 'Serbia', :iso => 'RS', :phonecode => 381},
                              {:name => 'Seychelles', :iso => 'SC', :phonecode => 248},
                              {:name => 'Sierra Leone', :iso => 'SL', :phonecode => 232},
                              {:name => 'Singapore', :iso => 'SG', :phonecode => 65},
                              {:name => 'Slovakia', :iso => 'SK', :phonecode => 421},
                              {:name => 'Slovenia', :iso => 'SI', :phonecode => 386},
                              {:name => 'Solomon Islands', :iso => 'SB', :phonecode => 677},
                              {:name => 'Somalia', :iso => 'SO', :phonecode => 252},
                              {:name => 'South Africa', :iso => 'ZA', :phonecode => 27},
                              {:name => 'South Georgia and The South Sandwich Islands', :iso => 'GS', :phonecode => 0},
                              {:name => 'Spain', :iso => 'ES', :phonecode => 34},
                              {:name => 'Sri Lanka', :iso => 'LK', :phonecode => 94 },
                              {:name => 'Sudan', :iso => 'SD', :phonecode => 249},
                              {:name => 'Suriname', :iso => 'SR', :phonecode => 597},
                              {:name => 'Svalbard and Jan Mayen', :iso => 'SJ', :phonecode => 47},
                              {:name => 'Swaziland', :iso => 'SZ', :phonecode => 268},
                              {:name => 'Sweden', :iso => 'SE', :phonecode => 46},
                              {:name => 'Switzerland', :iso => 'CH', :phonecode => 41},
                              {:name => 'Syrian Arab Republic', :iso => 'SY', :phonecode => 963},
                              {:name => 'Taiwan, Province of China', :iso => 'TW', :phonecode => 886},
                              {:name => 'Tajikistan', :iso => 'TJ', :phonecode => 992},
                              {:name => 'Tanzania, United Republic of', :iso => 'TZ', :phonecode => 255},
                              {:name => 'Thailand', :iso => 'TH', :phonecode => 66},
                              {:name => 'Timor-Leste', :iso => 'TL', :phonecode => 670},
                              {:name => 'Togo', :iso => 'TG', :phonecode => 228},
                              {:name => 'Tokelau', :iso => 'TK', :phonecode => 690},
                              {:name => 'Tonga', :iso => 'TO', :phonecode => 676},
                              {:name => 'Trinidad and Tobago', :iso => 'TT', :phonecode => 1868},
                              {:name => 'Tunisia', :iso => 'TN', :phonecode => 216},
                              {:name => 'Turkey', :iso => 'TR', :phonecode => 90},
                              {:name => 'Turkmenistan', :iso => 'TM', :phonecode => 7370},
                              {:name => 'Turks and Caicos Islands', :iso => 'TC', :phonecode => 1649},
                              {:name => 'Tuvalu', :iso => 'TV', :phonecode => 688},
                              {:name => 'Uganda', :iso => 'UG', :phonecode => 256},
                              {:name => 'Ukraine', :iso => 'UA', :phonecode => 380},
                              {:name => 'United Arab Emirates', :iso => 'AE', :phonecode => 971},
                              {:name => 'United Kingdom', :iso => 'GB', :phonecode => 44},
                              {:name => 'United States', :iso => 'US', :phonecode => 1},
                              {:name => 'United States Minor Outlying Islands', :iso => 'UM', :phonecode => 1},
                              {:name => 'Uruguay', :iso => 'UY', :phonecode => 598},
                              {:name => 'Uzbekistan', :iso => 'UZ', :phonecode => 998},
                              {:name => 'Vanuatu', :iso => 'VU', :phonecode => 678},
                              {:name => 'Venezuela, Bolivarian Republic of', :iso => 'VE', :phonecode => 58},
                              {:name => 'Viet Nam', :iso => 'VN', :phonecode => 84},
                              {:name => 'Virgin Islands, British', :iso => 'VG', :phonecode => 1284},
                              {:name => 'Virgin Islands, U.S.', :iso => 'VI', :phonecode => 1340},
                              {:name => 'Wallis and Futuna', :iso => 'WF', :phonecode => 681},
                              {:name => 'Western Sahara', :iso => 'EH', :phonecode => 212},
                              {:name => 'Yemen', :iso => 'YE', :phonecode => 967},
                              {:name => 'Zambia', :iso => 'ZM', :phonecode => 260},
                              {:name => 'Zimbabwe', :iso => 'ZW', :phonecode => 263}
])
